#pragma line 1 "Prova_casa/src/zhang_convolution_quant.c" ::: 0
#pragma line 1 "Prova_casa/src/zhang_convolution_quant.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 296 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 12
#pragma line 7 "<command line>" 2 ::: 128
#pragma line 1 "<built-in>" 2 ::: 129
#pragma line 1 "Prova_casa/src/zhang_convolution_quant.c" 2 ::: 130
#pragma line 1 "Prova_casa/src/net_config.h" 1 ::: 131
#pragma line 66 "Prova_casa/src/net_config.h" ::: 132
#pragma line 2 "Prova_casa/src/zhang_convolution_quant.c" 2 ::: 137
#pragma line 1 "Prova_casa/src/net_types.h" 1 ::: 138
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 139
#pragma line 33 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 3 ::: 140
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 141
#pragma line 25 "/usr/include/stdint.h" 3 4 ::: 142
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 143
#pragma line 345 "/usr/include/features.h" 3 4 ::: 144
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 145
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 146
#pragma line 367 "/usr/include/features.h" 3 4 ::: 147
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 148
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 149
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 150
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 151
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 152
#pragma line 391 "/usr/include/features.h" 3 4 ::: 153
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 154
#pragma line 10 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 3 4 ::: 155
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 156
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 157
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 158
#pragma line 26 "/usr/include/stdint.h" 2 3 4 ::: 159
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 160
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 161
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 162
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 163
#pragma line 65 "/usr/include/stdint.h" 3 4 ::: 192
#pragma line 90 "/usr/include/stdint.h" 3 4 ::: 209
#pragma line 103 "/usr/include/stdint.h" 3 4 ::: 215
#pragma line 119 "/usr/include/stdint.h" 3 4 ::: 221
#pragma line 134 "/usr/include/stdint.h" 3 4 ::: 226
#pragma line 34 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 229
#pragma line 2 "Prova_casa/src/net_types.h" 2 ::: 230
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" 1 ::: 231
#pragma line 62 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" ::: 232
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 233
#pragma line 32 "/usr/include/string.h" 3 4 ::: 234
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 235
#pragma line 31 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 236
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 247
#pragma line 42 "/usr/include/string.h" 3 4 ::: 248
#pragma line 92 "/usr/include/string.h" 3 4 ::: 274
#pragma line 125 "/usr/include/string.h" 3 4 ::: 277
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 313
#pragma line 27 "/usr/include/xlocale.h" 3 4 ::: 314
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 331
#pragma line 231 "/usr/include/string.h" 3 4 ::: 353
#pragma line 258 "/usr/include/string.h" 3 4 ::: 356
#pragma line 280 "/usr/include/string.h" 3 4 ::: 359
#pragma line 310 "/usr/include/string.h" 3 4 ::: 366
#pragma line 337 "/usr/include/string.h" 3 4 ::: 369
#pragma line 394 "/usr/include/string.h" 3 4 ::: 390
#pragma line 422 "/usr/include/string.h" 3 4 ::: 406
#pragma line 440 "/usr/include/string.h" 3 4 ::: 408
#pragma line 484 "/usr/include/string.h" 3 4 ::: 428
#pragma line 512 "/usr/include/string.h" 3 4 ::: 431
#pragma line 529 "/usr/include/string.h" 3 4 ::: 439
#pragma line 552 "/usr/include/string.h" 3 4 ::: 446
#pragma line 63 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" 2 ::: 470
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 471
#pragma line 33 "/usr/include/stdio.h" 3 4 ::: 472
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 473
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 474
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 476
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 477
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 478
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 479
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 506
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 507
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 508
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 577
#pragma line 64 "/usr/include/stdio.h" 3 4 ::: 591
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 593
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 594
#pragma line 31 "/usr/include/libio.h" 3 4 ::: 595
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 596
#pragma line 15 "/usr/include/_G_config.h" 3 4 ::: 597
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 598
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 599
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 604
#pragma line 82 "/usr/include/wchar.h" 3 4 ::: 605
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 619
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 630
#pragma line 49 "/usr/include/libio.h" 3 4 ::: 631
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 632
#pragma line 30 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 3 4 ::: 633
#pragma line 48 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 3 4 ::: 635
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 637
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 638
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 658
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 669
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 710
#pragma line 333 "/usr/include/libio.h" 3 4 ::: 740
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 762
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 766
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 781
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 793
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 799
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 801
#pragma line 164 "/usr/include/stdio.h" 3 4 ::: 811
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 812
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 813
#pragma line 195 "/usr/include/stdio.h" 3 4 ::: 836
#pragma line 209 "/usr/include/stdio.h" 3 4 ::: 838
#pragma line 227 "/usr/include/stdio.h" 3 4 ::: 846
#pragma line 237 "/usr/include/stdio.h" 3 4 ::: 849
#pragma line 252 "/usr/include/stdio.h" 3 4 ::: 856
#pragma line 272 "/usr/include/stdio.h" 3 4 ::: 858
#pragma line 306 "/usr/include/stdio.h" 3 4 ::: 868
#pragma line 319 "/usr/include/stdio.h" 3 4 ::: 870
#pragma line 356 "/usr/include/stdio.h" 3 4 ::: 900
#pragma line 412 "/usr/include/stdio.h" 3 4 ::: 938
#pragma line 425 "/usr/include/stdio.h" 3 4 ::: 944
#pragma line 443 "/usr/include/stdio.h" 3 4 ::: 955
#pragma line 471 "/usr/include/stdio.h" 3 4 ::: 962
#pragma line 494 "/usr/include/stdio.h" 3 4 ::: 978
#pragma line 531 "/usr/include/stdio.h" 3 4 ::: 992
#pragma line 550 "/usr/include/stdio.h" 3 4 ::: 1001
#pragma line 561 "/usr/include/stdio.h" 3 4 ::: 1004
#pragma line 573 "/usr/include/stdio.h" 3 4 ::: 1006
#pragma line 594 "/usr/include/stdio.h" 3 4 ::: 1015
#pragma line 622 "/usr/include/stdio.h" 3 4 ::: 1036
#pragma line 638 "/usr/include/stdio.h" 3 4 ::: 1039
#pragma line 665 "/usr/include/stdio.h" 3 4 ::: 1041
#pragma line 689 "/usr/include/stdio.h" 3 4 ::: 1058
#pragma line 737 "/usr/include/stdio.h" 3 4 ::: 1087
#pragma line 749 "/usr/include/stdio.h" 3 4 ::: 1092
#pragma line 773 "/usr/include/stdio.h" 3 4 ::: 1104
#pragma line 798 "/usr/include/stdio.h" 3 4 ::: 1111
#pragma line 826 "/usr/include/stdio.h" 3 4 ::: 1118
#pragma line 846 "/usr/include/stdio.h" 3 4 ::: 1131
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1140
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 3 4 ::: 1141
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1144
#pragma line 872 "/usr/include/stdio.h" 3 4 ::: 1155
#pragma line 912 "/usr/include/stdio.h" 3 4 ::: 1169
#pragma line 64 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" 2 ::: 1178
#pragma line 77 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" ::: 1179
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 1180
#pragma line 57 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_apint.h" ::: 1181
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" 1 ::: 1182
#pragma line 97 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 1183
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 1184
#pragma line 98 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 2223
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 2224
#pragma line 99 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 3251
#pragma line 108 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 3252
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 3253
#pragma line 109 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 4292
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 4293
#pragma line 110 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 5320
#pragma line 131 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 5321
#pragma line 58 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5324
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" 1 ::: 5325
#pragma line 59 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5326
#pragma line 78 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" 2 ::: 5327
#pragma line 3 "Prova_casa/src/net_types.h" 2 ::: 5328
#pragma line 21 "Prova_casa/src/net_types.h" ::: 5329
#pragma line 3 "Prova_casa/src/zhang_convolution_quant.c" 2 ::: 5430
#pragma line 1 "Prova_casa/src/zhang_convolution_quant.h" 1 ::: 5431
#pragma line 4 "Prova_casa/src/zhang_convolution_quant.c" 2 ::: 5445
#pragma line 25 "Prova_casa/src/zhang_convolution_quant.c" ::: 5446
