#pragma line 1 "Prova_casa/src/zhang_convolution_quant.c" ::: -10
#pragma line 1 "Prova_casa/src/zhang_convolution_quant.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 296 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 2
#pragma line 7 "<command line>" 2 ::: 118
#pragma line 1 "<built-in>" 2 ::: 119
#pragma line 1 "Prova_casa/src/zhang_convolution_quant.c" 2 ::: 120
#pragma line 1 "Prova_casa/src/net_config.h" 1 ::: 121
#pragma line 66 "Prova_casa/src/net_config.h" ::: 122
#pragma line 2 "Prova_casa/src/zhang_convolution_quant.c" 2 ::: 127
#pragma line 1 "Prova_casa/src/net_types.h" 1 ::: 128
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 129
#pragma line 33 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 3 ::: 130
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 131
#pragma line 25 "/usr/include/stdint.h" 3 4 ::: 132
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 133
#pragma line 345 "/usr/include/features.h" 3 4 ::: 134
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 135
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 136
#pragma line 367 "/usr/include/features.h" 3 4 ::: 137
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 138
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 139
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 140
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 141
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 142
#pragma line 391 "/usr/include/features.h" 3 4 ::: 143
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 144
#pragma line 10 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 3 4 ::: 145
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 146
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 147
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 148
#pragma line 26 "/usr/include/stdint.h" 2 3 4 ::: 149
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 150
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 151
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 152
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 153
#pragma line 65 "/usr/include/stdint.h" 3 4 ::: 182
#pragma line 90 "/usr/include/stdint.h" 3 4 ::: 199
#pragma line 103 "/usr/include/stdint.h" 3 4 ::: 205
#pragma line 119 "/usr/include/stdint.h" 3 4 ::: 211
#pragma line 134 "/usr/include/stdint.h" 3 4 ::: 216
#pragma line 34 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 219
#pragma line 2 "Prova_casa/src/net_types.h" 2 ::: 220
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" 1 ::: 221
#pragma line 62 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" ::: 222
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 223
#pragma line 32 "/usr/include/string.h" 3 4 ::: 224
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 225
#pragma line 31 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 226
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 237
#pragma line 42 "/usr/include/string.h" 3 4 ::: 238
#pragma line 92 "/usr/include/string.h" 3 4 ::: 264
#pragma line 125 "/usr/include/string.h" 3 4 ::: 267
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 303
#pragma line 27 "/usr/include/xlocale.h" 3 4 ::: 304
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 321
#pragma line 231 "/usr/include/string.h" 3 4 ::: 343
#pragma line 258 "/usr/include/string.h" 3 4 ::: 346
#pragma line 280 "/usr/include/string.h" 3 4 ::: 349
#pragma line 310 "/usr/include/string.h" 3 4 ::: 356
#pragma line 337 "/usr/include/string.h" 3 4 ::: 359
#pragma line 394 "/usr/include/string.h" 3 4 ::: 380
#pragma line 422 "/usr/include/string.h" 3 4 ::: 396
#pragma line 440 "/usr/include/string.h" 3 4 ::: 398
#pragma line 484 "/usr/include/string.h" 3 4 ::: 418
#pragma line 512 "/usr/include/string.h" 3 4 ::: 421
#pragma line 529 "/usr/include/string.h" 3 4 ::: 429
#pragma line 552 "/usr/include/string.h" 3 4 ::: 436
#pragma line 63 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" 2 ::: 460
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 461
#pragma line 33 "/usr/include/stdio.h" 3 4 ::: 462
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 463
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 464
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 466
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 467
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 468
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 469
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 496
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 497
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 498
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 567
#pragma line 64 "/usr/include/stdio.h" 3 4 ::: 581
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 583
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 584
#pragma line 31 "/usr/include/libio.h" 3 4 ::: 585
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 586
#pragma line 15 "/usr/include/_G_config.h" 3 4 ::: 587
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 588
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 589
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 594
#pragma line 82 "/usr/include/wchar.h" 3 4 ::: 595
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 609
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 620
#pragma line 49 "/usr/include/libio.h" 3 4 ::: 621
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 622
#pragma line 30 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 3 4 ::: 623
#pragma line 48 "/media/dati/dante/Xilinx/Vivado/2017.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 3 4 ::: 625
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 627
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 628
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 648
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 659
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 700
#pragma line 333 "/usr/include/libio.h" 3 4 ::: 730
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 752
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 756
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 771
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 783
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 789
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 791
#pragma line 164 "/usr/include/stdio.h" 3 4 ::: 801
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 802
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 803
#pragma line 195 "/usr/include/stdio.h" 3 4 ::: 826
#pragma line 209 "/usr/include/stdio.h" 3 4 ::: 828
#pragma line 227 "/usr/include/stdio.h" 3 4 ::: 836
#pragma line 237 "/usr/include/stdio.h" 3 4 ::: 839
#pragma line 252 "/usr/include/stdio.h" 3 4 ::: 846
#pragma line 272 "/usr/include/stdio.h" 3 4 ::: 848
#pragma line 306 "/usr/include/stdio.h" 3 4 ::: 858
#pragma line 319 "/usr/include/stdio.h" 3 4 ::: 860
#pragma line 356 "/usr/include/stdio.h" 3 4 ::: 890
#pragma line 412 "/usr/include/stdio.h" 3 4 ::: 928
#pragma line 425 "/usr/include/stdio.h" 3 4 ::: 934
#pragma line 443 "/usr/include/stdio.h" 3 4 ::: 945
#pragma line 471 "/usr/include/stdio.h" 3 4 ::: 952
#pragma line 494 "/usr/include/stdio.h" 3 4 ::: 968
#pragma line 531 "/usr/include/stdio.h" 3 4 ::: 982
#pragma line 550 "/usr/include/stdio.h" 3 4 ::: 991
#pragma line 561 "/usr/include/stdio.h" 3 4 ::: 994
#pragma line 573 "/usr/include/stdio.h" 3 4 ::: 996
#pragma line 594 "/usr/include/stdio.h" 3 4 ::: 1005
#pragma line 622 "/usr/include/stdio.h" 3 4 ::: 1026
#pragma line 638 "/usr/include/stdio.h" 3 4 ::: 1029
#pragma line 665 "/usr/include/stdio.h" 3 4 ::: 1031
#pragma line 689 "/usr/include/stdio.h" 3 4 ::: 1048
#pragma line 737 "/usr/include/stdio.h" 3 4 ::: 1077
#pragma line 749 "/usr/include/stdio.h" 3 4 ::: 1082
#pragma line 773 "/usr/include/stdio.h" 3 4 ::: 1094
#pragma line 798 "/usr/include/stdio.h" 3 4 ::: 1101
#pragma line 826 "/usr/include/stdio.h" 3 4 ::: 1108
#pragma line 846 "/usr/include/stdio.h" 3 4 ::: 1121
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1130
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 3 4 ::: 1131
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1134
#pragma line 872 "/usr/include/stdio.h" 3 4 ::: 1145
#pragma line 912 "/usr/include/stdio.h" 3 4 ::: 1159
#pragma line 64 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" 2 ::: 1168
#pragma line 77 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" ::: 1169
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 1170
#pragma line 57 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_apint.h" ::: 1171
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" 1 ::: 1172
#pragma line 97 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 1173
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 1174
#pragma line 98 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 2213
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 2214
#pragma line 99 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 3241
#pragma line 108 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 3242
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 3243
#pragma line 109 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 4282
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 4283
#pragma line 110 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 5310
#pragma line 131 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 5311
#pragma line 58 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5314
#pragma line 1 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" 1 ::: 5315
#pragma line 59 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5316
#pragma line 78 "/media/dati/dante/Xilinx/Vivado/2017.3/common/technology/autopilot/ap_cint.h" 2 ::: 5317
#pragma line 3 "Prova_casa/src/net_types.h" 2 ::: 5318
#pragma line 21 "Prova_casa/src/net_types.h" ::: 5319
#pragma line 3 "Prova_casa/src/zhang_convolution_quant.c" 2 ::: 5420
#pragma line 1 "Prova_casa/src/zhang_convolution_quant.h" 1 ::: 5421
#pragma line 4 "Prova_casa/src/zhang_convolution_quant.c" 2 ::: 5435
#pragma line 25 "Prova_casa/src/zhang_convolution_quant.c" ::: 5436
