// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module zhang_cnn_read_input (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_input_r_AWVALID,
        m_axi_input_r_AWREADY,
        m_axi_input_r_AWADDR,
        m_axi_input_r_AWID,
        m_axi_input_r_AWLEN,
        m_axi_input_r_AWSIZE,
        m_axi_input_r_AWBURST,
        m_axi_input_r_AWLOCK,
        m_axi_input_r_AWCACHE,
        m_axi_input_r_AWPROT,
        m_axi_input_r_AWQOS,
        m_axi_input_r_AWREGION,
        m_axi_input_r_AWUSER,
        m_axi_input_r_WVALID,
        m_axi_input_r_WREADY,
        m_axi_input_r_WDATA,
        m_axi_input_r_WSTRB,
        m_axi_input_r_WLAST,
        m_axi_input_r_WID,
        m_axi_input_r_WUSER,
        m_axi_input_r_ARVALID,
        m_axi_input_r_ARREADY,
        m_axi_input_r_ARADDR,
        m_axi_input_r_ARID,
        m_axi_input_r_ARLEN,
        m_axi_input_r_ARSIZE,
        m_axi_input_r_ARBURST,
        m_axi_input_r_ARLOCK,
        m_axi_input_r_ARCACHE,
        m_axi_input_r_ARPROT,
        m_axi_input_r_ARQOS,
        m_axi_input_r_ARREGION,
        m_axi_input_r_ARUSER,
        m_axi_input_r_RVALID,
        m_axi_input_r_RREADY,
        m_axi_input_r_RDATA,
        m_axi_input_r_RLAST,
        m_axi_input_r_RID,
        m_axi_input_r_RUSER,
        m_axi_input_r_RRESP,
        m_axi_input_r_BVALID,
        m_axi_input_r_BREADY,
        m_axi_input_r_BRESP,
        m_axi_input_r_BID,
        m_axi_input_r_BUSER,
        image1,
        curr_layer_in_w,
        curr_layer_in_h,
        curr_layer_out_w,
        curr_layer_out_h,
        curr_layer_in_ch,
        curr_layer_ker_w,
        curr_layer_ker_h,
        curr_layer_str_w,
        curr_layer_str_h,
        ti,
        row,
        col,
        inputfm_address0,
        inputfm_ce0,
        inputfm_we0,
        inputfm_d0
);

parameter    ap_ST_st1_fsm_0 = 22'b1;
parameter    ap_ST_st2_fsm_1 = 22'b10;
parameter    ap_ST_st3_fsm_2 = 22'b100;
parameter    ap_ST_st4_fsm_3 = 22'b1000;
parameter    ap_ST_st5_fsm_4 = 22'b10000;
parameter    ap_ST_st6_fsm_5 = 22'b100000;
parameter    ap_ST_st7_fsm_6 = 22'b1000000;
parameter    ap_ST_st8_fsm_7 = 22'b10000000;
parameter    ap_ST_st9_fsm_8 = 22'b100000000;
parameter    ap_ST_st10_fsm_9 = 22'b1000000000;
parameter    ap_ST_st11_fsm_10 = 22'b10000000000;
parameter    ap_ST_st12_fsm_11 = 22'b100000000000;
parameter    ap_ST_st13_fsm_12 = 22'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 22'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 22'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 22'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 22'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 22'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 22'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 22'b10000000000000000000;
parameter    ap_ST_pp0_stg0_fsm_20 = 22'b100000000000000000000;
parameter    ap_ST_st45_fsm_21 = 22'b1000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv31_0 = 31'b0000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv32_19 = 32'b11001;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv31_1 = 31'b1;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv32_15 = 32'b10101;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_input_r_AWVALID;
input   m_axi_input_r_AWREADY;
output  [31:0] m_axi_input_r_AWADDR;
output  [0:0] m_axi_input_r_AWID;
output  [31:0] m_axi_input_r_AWLEN;
output  [2:0] m_axi_input_r_AWSIZE;
output  [1:0] m_axi_input_r_AWBURST;
output  [1:0] m_axi_input_r_AWLOCK;
output  [3:0] m_axi_input_r_AWCACHE;
output  [2:0] m_axi_input_r_AWPROT;
output  [3:0] m_axi_input_r_AWQOS;
output  [3:0] m_axi_input_r_AWREGION;
output  [0:0] m_axi_input_r_AWUSER;
output   m_axi_input_r_WVALID;
input   m_axi_input_r_WREADY;
output  [31:0] m_axi_input_r_WDATA;
output  [3:0] m_axi_input_r_WSTRB;
output   m_axi_input_r_WLAST;
output  [0:0] m_axi_input_r_WID;
output  [0:0] m_axi_input_r_WUSER;
output   m_axi_input_r_ARVALID;
input   m_axi_input_r_ARREADY;
output  [31:0] m_axi_input_r_ARADDR;
output  [0:0] m_axi_input_r_ARID;
output  [31:0] m_axi_input_r_ARLEN;
output  [2:0] m_axi_input_r_ARSIZE;
output  [1:0] m_axi_input_r_ARBURST;
output  [1:0] m_axi_input_r_ARLOCK;
output  [3:0] m_axi_input_r_ARCACHE;
output  [2:0] m_axi_input_r_ARPROT;
output  [3:0] m_axi_input_r_ARQOS;
output  [3:0] m_axi_input_r_ARREGION;
output  [0:0] m_axi_input_r_ARUSER;
input   m_axi_input_r_RVALID;
output   m_axi_input_r_RREADY;
input  [31:0] m_axi_input_r_RDATA;
input   m_axi_input_r_RLAST;
input  [0:0] m_axi_input_r_RID;
input  [0:0] m_axi_input_r_RUSER;
input  [1:0] m_axi_input_r_RRESP;
input   m_axi_input_r_BVALID;
output   m_axi_input_r_BREADY;
input  [1:0] m_axi_input_r_BRESP;
input  [0:0] m_axi_input_r_BID;
input  [0:0] m_axi_input_r_BUSER;
input  [29:0] image1;
input  [31:0] curr_layer_in_w;
input  [31:0] curr_layer_in_h;
input  [31:0] curr_layer_out_w;
input  [31:0] curr_layer_out_h;
input  [31:0] curr_layer_in_ch;
input  [31:0] curr_layer_ker_w;
input  [31:0] curr_layer_ker_h;
input  [31:0] curr_layer_str_w;
input  [31:0] curr_layer_str_h;
input  [31:0] ti;
input  [31:0] row;
input  [31:0] col;
output  [15:0] inputfm_address0;
output   inputfm_ce0;
output   inputfm_we0;
output  [31:0] inputfm_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_input_r_ARVALID;
reg m_axi_input_r_RREADY;
reg inputfm_ce0;
reg inputfm_we0;

(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_39;
reg    input_r_blk_n_AR;
reg    ap_reg_ppiten_pp0_it15;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_reg_ppiten_pp0_it3;
reg    ap_reg_ppiten_pp0_it4;
reg    ap_reg_ppiten_pp0_it5;
reg    ap_reg_ppiten_pp0_it6;
reg    ap_reg_ppiten_pp0_it7;
reg    ap_reg_ppiten_pp0_it8;
reg    ap_reg_ppiten_pp0_it9;
reg    ap_reg_ppiten_pp0_it10;
reg    ap_reg_ppiten_pp0_it11;
reg    ap_reg_ppiten_pp0_it12;
reg    ap_reg_ppiten_pp0_it13;
reg    ap_reg_ppiten_pp0_it14;
reg    ap_reg_ppiten_pp0_it16;
reg    ap_reg_ppiten_pp0_it17;
reg    ap_reg_ppiten_pp0_it18;
reg    ap_reg_ppiten_pp0_it19;
reg    ap_reg_ppiten_pp0_it20;
reg    ap_reg_ppiten_pp0_it21;
reg    ap_reg_ppiten_pp0_it22;
reg    ap_reg_ppiten_pp0_it23;
reg   [0:0] tmp_112_reg_800;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter14;
reg    input_r_blk_n_R;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter21;
reg   [30:0] itr_reg_196;
reg   [31:0] i_reg_207;
reg   [31:0] j_reg_218;
reg   [31:0] jj_reg_230;
wire   [31:0] grp_fu_253_p2;
reg   [31:0] tmp_89_reg_676;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_200;
wire   [31:0] grp_fu_247_p2;
reg   [31:0] tmp_92_reg_681;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_211;
wire   [31:0] n_rows_fu_274_p3;
reg   [31:0] n_rows_reg_700;
wire   [0:0] tmp_101_fu_294_p2;
reg   [0:0] tmp_101_reg_711;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_228;
wire  signed [31:0] n_rows_2_fu_334_p3;
reg  signed [31:0] n_rows_2_reg_732;
wire  signed [31:0] n_depth_1_fu_357_p3;
reg  signed [31:0] n_depth_1_reg_738;
wire   [31:0] grp_fu_381_p2;
reg   [31:0] tmp_95_reg_743;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_245;
wire   [31:0] grp_fu_288_p2;
reg   [31:0] tmp_98_reg_748;
wire   [31:0] n_cols_fu_402_p3;
reg   [31:0] n_cols_reg_753;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_256;
wire   [31:0] tmp5_fu_410_p2;
reg   [31:0] tmp5_reg_759;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_267;
wire  signed [31:0] n_cols_2_fu_438_p3;
reg  signed [31:0] n_cols_2_reg_774;
wire  signed [31:0] grp_fu_377_p2;
reg  signed [31:0] tmp1_reg_780;
wire   [31:0] grp_fu_416_p2;
reg   [31:0] tmp_88_reg_785;
reg    ap_sig_cseq_ST_st19_fsm_18;
reg    ap_sig_282;
wire   [31:0] grp_fu_451_p2;
reg   [31:0] tmp_111_reg_790;
reg    ap_sig_cseq_ST_st20_fsm_19;
reg    ap_sig_291;
wire   [32:0] sext_cast_fu_455_p1;
reg   [32:0] sext_cast_reg_795;
wire   [0:0] tmp_112_fu_463_p2;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_20;
reg    ap_sig_301;
reg    ap_sig_ioackin_m_axi_input_r_ARREADY;
reg    ap_sig_309;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter1;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter2;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter3;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter4;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter5;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter6;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter7;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter8;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter9;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter10;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter11;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter12;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter13;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter15;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter16;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter17;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter18;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter19;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter20;
reg   [0:0] ap_reg_ppstg_tmp_112_reg_800_pp0_iter22;
wire   [30:0] itr_2_fu_468_p2;
wire   [0:0] tmp_113_fu_474_p2;
reg   [0:0] tmp_113_reg_809;
wire   [0:0] tmp_114_fu_493_p2;
reg   [0:0] tmp_114_reg_814;
wire   [31:0] i_2_fu_504_p3;
reg   [31:0] i_2_reg_819;
reg   [31:0] ap_reg_ppstg_i_2_reg_819_pp0_iter1;
reg   [31:0] ap_reg_ppstg_i_2_reg_819_pp0_iter2;
reg   [31:0] ap_reg_ppstg_i_2_reg_819_pp0_iter3;
reg   [31:0] ap_reg_ppstg_i_2_reg_819_pp0_iter4;
reg   [31:0] ap_reg_ppstg_i_2_reg_819_pp0_iter5;
reg   [31:0] ap_reg_ppstg_i_2_reg_819_pp0_iter6;
wire  signed [31:0] jj_1_fu_512_p3;
reg  signed [31:0] jj_1_reg_826;
wire   [31:0] j_2_fu_524_p3;
reg   [31:0] j_2_reg_834;
reg   [31:0] ap_reg_ppstg_j_2_reg_834_pp0_iter2;
reg   [31:0] ap_reg_ppstg_j_2_reg_834_pp0_iter3;
reg   [31:0] ap_reg_ppstg_j_2_reg_834_pp0_iter4;
reg   [31:0] ap_reg_ppstg_j_2_reg_834_pp0_iter5;
reg   [31:0] ap_reg_ppstg_j_2_reg_834_pp0_iter6;
reg   [31:0] ap_reg_ppstg_j_2_reg_834_pp0_iter7;
reg   [31:0] ap_reg_ppstg_j_2_reg_834_pp0_iter8;
reg   [31:0] ap_reg_ppstg_j_2_reg_834_pp0_iter9;
reg   [31:0] ap_reg_ppstg_j_2_reg_834_pp0_iter10;
reg   [31:0] ap_reg_ppstg_j_2_reg_834_pp0_iter11;
reg   [31:0] ap_reg_ppstg_j_2_reg_834_pp0_iter12;
wire   [16:0] tmp_140_fu_607_p2;
reg   [16:0] tmp_140_reg_839;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter2;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter3;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter4;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter5;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter6;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter7;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter8;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter9;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter10;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter11;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter12;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter13;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter14;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter15;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter16;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter17;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter18;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter19;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter20;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter21;
reg   [16:0] ap_reg_ppstg_tmp_140_reg_839_pp0_iter22;
wire   [31:0] j_4_fu_613_p2;
wire   [31:0] grp_fu_532_p2;
reg   [31:0] tmp_115_reg_849;
wire  signed [31:0] tmp16_fu_623_p2;
reg  signed [31:0] tmp16_reg_854;
wire   [31:0] tmp_116_fu_636_p2;
reg   [31:0] tmp_116_reg_859;
reg   [31:0] input_addr_reg_864;
reg   [31:0] input_addr_read_reg_870;
reg   [31:0] i_phi_fu_211_p4;
reg   [31:0] j_phi_fu_222_p4;
reg   [31:0] jj_phi_fu_234_p4;
wire   [63:0] tmp_141_cast_fu_660_p1;
wire  signed [63:0] sum_cast_fu_650_p1;
reg    ap_reg_ioackin_m_axi_input_r_ARREADY;
wire  signed [31:0] grp_fu_247_p1;
wire   [5:0] grp_fu_253_p1;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_500;
wire   [31:0] tmp_90_fu_258_p2;
wire   [31:0] tmp_93_fu_263_p2;
wire   [0:0] tmp_94_fu_268_p2;
wire  signed [31:0] grp_fu_288_p1;
wire  signed [31:0] tmp_102_fu_317_p0;
wire   [31:0] tmp_102_fu_317_p2;
wire  signed [31:0] tmp_103_fu_322_p1;
wire  signed [31:0] tmp_104_fu_328_p0;
wire  signed [31:0] tmp_104_fu_328_p1;
wire   [0:0] tmp_103_fu_322_p2;
wire   [31:0] tmp_104_fu_328_p2;
wire  signed [31:0] tmp_108_fu_341_p0;
wire   [31:0] n_depth_fu_311_p3;
wire   [31:0] tmp_108_fu_341_p2;
wire  signed [31:0] tmp_110_fu_352_p1;
wire   [0:0] tmp_109_fu_347_p2;
wire   [31:0] tmp_110_fu_352_p2;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_560;
wire   [5:0] grp_fu_381_p1;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_569;
wire   [31:0] tmp_96_fu_386_p2;
wire   [31:0] tmp_99_fu_391_p2;
wire   [0:0] tmp_100_fu_396_p2;
wire   [31:0] grp_fu_300_p2;
wire   [31:0] grp_fu_306_p2;
wire  signed [31:0] tmp_105_fu_421_p0;
wire   [31:0] tmp_105_fu_421_p2;
wire  signed [31:0] tmp_106_fu_426_p1;
wire  signed [31:0] tmp_107_fu_432_p0;
wire  signed [31:0] tmp_107_fu_432_p1;
wire   [0:0] tmp_106_fu_426_p2;
wire   [31:0] tmp_107_fu_432_p2;
reg    ap_sig_cseq_ST_st15_fsm_14;
reg    ap_sig_608;
wire   [31:0] itr_cast_fu_459_p1;
wire   [31:0] i_4_fu_479_p2;
wire   [31:0] p_i_fu_485_p3;
wire   [31:0] jj_2_fu_498_p2;
wire   [0:0] tmp_74_fu_520_p2;
wire   [37:0] tmp_133_fu_543_p3;
wire   [35:0] tmp_134_fu_554_p3;
wire  signed [38:0] p_shl3_cast_fu_550_p1;
wire  signed [38:0] p_shl4_cast_fu_561_p1;
wire  signed [38:0] tmp_119_cast_fu_540_p1;
wire   [38:0] tmp_135_fu_565_p2;
wire   [38:0] tmp_136_fu_571_p2;
wire   [10:0] tmp_137_fu_577_p1;
wire   [12:0] tmp_138_fu_589_p1;
wire   [16:0] p_shl_cast_fu_581_p3;
wire   [16:0] p_shl2_cast_fu_593_p3;
wire   [16:0] tmp_132_fu_536_p1;
wire   [16:0] tmp_139_fu_601_p2;
wire   [31:0] tmp_fu_619_p2;
wire   [31:0] grp_fu_628_p2;
wire   [31:0] tmp2_fu_632_p2;
wire  signed [32:0] tmp_117_cast_fu_642_p1;
wire   [32:0] sum_fu_645_p2;
reg    grp_fu_532_ce;
reg    grp_fu_628_ce;
reg    ap_sig_cseq_ST_st45_fsm_21;
reg    ap_sig_822;
reg   [21:0] ap_NS_fsm;
reg    ap_sig_874;
reg    ap_sig_173;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'b1;
#0 ap_reg_ppiten_pp0_it15 = 1'b0;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ppiten_pp0_it3 = 1'b0;
#0 ap_reg_ppiten_pp0_it4 = 1'b0;
#0 ap_reg_ppiten_pp0_it5 = 1'b0;
#0 ap_reg_ppiten_pp0_it6 = 1'b0;
#0 ap_reg_ppiten_pp0_it7 = 1'b0;
#0 ap_reg_ppiten_pp0_it8 = 1'b0;
#0 ap_reg_ppiten_pp0_it9 = 1'b0;
#0 ap_reg_ppiten_pp0_it10 = 1'b0;
#0 ap_reg_ppiten_pp0_it11 = 1'b0;
#0 ap_reg_ppiten_pp0_it12 = 1'b0;
#0 ap_reg_ppiten_pp0_it13 = 1'b0;
#0 ap_reg_ppiten_pp0_it14 = 1'b0;
#0 ap_reg_ppiten_pp0_it16 = 1'b0;
#0 ap_reg_ppiten_pp0_it17 = 1'b0;
#0 ap_reg_ppiten_pp0_it18 = 1'b0;
#0 ap_reg_ppiten_pp0_it19 = 1'b0;
#0 ap_reg_ppiten_pp0_it20 = 1'b0;
#0 ap_reg_ppiten_pp0_it21 = 1'b0;
#0 ap_reg_ppiten_pp0_it22 = 1'b0;
#0 ap_reg_ppiten_pp0_it23 = 1'b0;
#0 ap_reg_ioackin_m_axi_input_r_ARREADY = 1'b0;
end

zhang_cnn_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
zhang_cnn_mul_32s_32s_32_6_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(curr_layer_str_h),
    .din1(grp_fu_247_p1),
    .ce(1'b1),
    .dout(grp_fu_247_p2)
);

zhang_cnn_mul_32s_6ns_32_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
zhang_cnn_mul_32s_6ns_32_3_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(curr_layer_str_h),
    .din1(grp_fu_253_p1),
    .ce(1'b1),
    .dout(grp_fu_253_p2)
);

zhang_cnn_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
zhang_cnn_mul_32s_32s_32_6_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(curr_layer_str_w),
    .din1(grp_fu_288_p1),
    .ce(1'b1),
    .dout(grp_fu_288_p2)
);

zhang_cnn_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
zhang_cnn_mul_32s_32s_32_6_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(curr_layer_in_h),
    .din1(ti),
    .ce(1'b1),
    .dout(grp_fu_300_p2)
);

zhang_cnn_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
zhang_cnn_mul_32s_32s_32_6_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(curr_layer_str_h),
    .din1(row),
    .ce(1'b1),
    .dout(grp_fu_306_p2)
);

zhang_cnn_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
zhang_cnn_mul_32s_32s_32_6_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(n_rows_2_reg_732),
    .din1(n_depth_1_reg_738),
    .ce(1'b1),
    .dout(grp_fu_377_p2)
);

zhang_cnn_mul_32s_6ns_32_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
zhang_cnn_mul_32s_6ns_32_3_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(curr_layer_str_w),
    .din1(grp_fu_381_p1),
    .ce(1'b1),
    .dout(grp_fu_381_p2)
);

zhang_cnn_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
zhang_cnn_mul_32s_32s_32_6_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(curr_layer_str_w),
    .din1(col),
    .ce(1'b1),
    .dout(grp_fu_416_p2)
);

zhang_cnn_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
zhang_cnn_mul_32s_32s_32_6_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp1_reg_780),
    .din1(n_cols_2_reg_774),
    .ce(1'b1),
    .dout(grp_fu_451_p2)
);

zhang_cnn_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
zhang_cnn_mul_32s_32s_32_6_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(jj_1_reg_826),
    .din1(curr_layer_in_h),
    .ce(grp_fu_532_ce),
    .dout(grp_fu_532_p2)
);

zhang_cnn_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
zhang_cnn_mul_32s_32s_32_6_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp16_reg_854),
    .din1(curr_layer_in_w),
    .ce(grp_fu_628_ce),
    .dout(grp_fu_628_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_m_axi_input_r_ARREADY <= 1'b0;
    end else begin
        if (ap_sig_173) begin
            if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
                ap_reg_ioackin_m_axi_input_r_ARREADY <= 1'b0;
            end else if (ap_sig_874) begin
                ap_reg_ioackin_m_axi_input_r_ARREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & (1'b0 == tmp_112_fu_463_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if ((1'b1 == ap_sig_cseq_ST_st20_fsm_19)) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == tmp_112_fu_463_p2))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if (((1'b1 == ap_sig_cseq_ST_st20_fsm_19) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & (1'b0 == tmp_112_fu_463_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it10 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it10 <= ap_reg_ppiten_pp0_it9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it11 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it11 <= ap_reg_ppiten_pp0_it10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it12 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it12 <= ap_reg_ppiten_pp0_it11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it13 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it13 <= ap_reg_ppiten_pp0_it12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it14 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it14 <= ap_reg_ppiten_pp0_it13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it15 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it15 <= ap_reg_ppiten_pp0_it14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it16 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it16 <= ap_reg_ppiten_pp0_it15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it17 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it17 <= ap_reg_ppiten_pp0_it16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it18 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it18 <= ap_reg_ppiten_pp0_it17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it19 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it19 <= ap_reg_ppiten_pp0_it18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it20 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it20 <= ap_reg_ppiten_pp0_it19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it21 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it21 <= ap_reg_ppiten_pp0_it20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it22 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it22 <= ap_reg_ppiten_pp0_it21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it23 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it23 <= ap_reg_ppiten_pp0_it22;
        end else if ((1'b1 == ap_sig_cseq_ST_st20_fsm_19)) begin
            ap_reg_ppiten_pp0_it23 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it9 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
            ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == tmp_112_reg_800))) begin
        i_reg_207 <= i_2_reg_819;
    end else if ((1'b1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        i_reg_207 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == tmp_112_fu_463_p2))) begin
        itr_reg_196 <= itr_2_fu_468_p2;
    end else if ((1'b1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        itr_reg_196 <= ap_const_lv31_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == tmp_112_reg_800))) begin
        j_reg_218 <= j_4_fu_613_p2;
    end else if ((1'b1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        j_reg_218 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == tmp_112_reg_800))) begin
        jj_reg_230 <= jj_1_reg_826;
    end else if ((1'b1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        jj_reg_230 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)))) begin
        ap_reg_ppstg_i_2_reg_819_pp0_iter1 <= i_2_reg_819;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter1 <= tmp_112_reg_800;
        tmp_112_reg_800 <= tmp_112_fu_463_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309))) begin
        ap_reg_ppstg_i_2_reg_819_pp0_iter2 <= ap_reg_ppstg_i_2_reg_819_pp0_iter1;
        ap_reg_ppstg_i_2_reg_819_pp0_iter3 <= ap_reg_ppstg_i_2_reg_819_pp0_iter2;
        ap_reg_ppstg_i_2_reg_819_pp0_iter4 <= ap_reg_ppstg_i_2_reg_819_pp0_iter3;
        ap_reg_ppstg_i_2_reg_819_pp0_iter5 <= ap_reg_ppstg_i_2_reg_819_pp0_iter4;
        ap_reg_ppstg_i_2_reg_819_pp0_iter6 <= ap_reg_ppstg_i_2_reg_819_pp0_iter5;
        ap_reg_ppstg_j_2_reg_834_pp0_iter10 <= ap_reg_ppstg_j_2_reg_834_pp0_iter9;
        ap_reg_ppstg_j_2_reg_834_pp0_iter11 <= ap_reg_ppstg_j_2_reg_834_pp0_iter10;
        ap_reg_ppstg_j_2_reg_834_pp0_iter12 <= ap_reg_ppstg_j_2_reg_834_pp0_iter11;
        ap_reg_ppstg_j_2_reg_834_pp0_iter2 <= j_2_reg_834;
        ap_reg_ppstg_j_2_reg_834_pp0_iter3 <= ap_reg_ppstg_j_2_reg_834_pp0_iter2;
        ap_reg_ppstg_j_2_reg_834_pp0_iter4 <= ap_reg_ppstg_j_2_reg_834_pp0_iter3;
        ap_reg_ppstg_j_2_reg_834_pp0_iter5 <= ap_reg_ppstg_j_2_reg_834_pp0_iter4;
        ap_reg_ppstg_j_2_reg_834_pp0_iter6 <= ap_reg_ppstg_j_2_reg_834_pp0_iter5;
        ap_reg_ppstg_j_2_reg_834_pp0_iter7 <= ap_reg_ppstg_j_2_reg_834_pp0_iter6;
        ap_reg_ppstg_j_2_reg_834_pp0_iter8 <= ap_reg_ppstg_j_2_reg_834_pp0_iter7;
        ap_reg_ppstg_j_2_reg_834_pp0_iter9 <= ap_reg_ppstg_j_2_reg_834_pp0_iter8;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter10 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter9;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter11 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter10;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter12 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter11;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter13 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter12;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter14 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter13;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter15 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter14;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter16 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter15;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter17 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter16;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter18 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter17;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter19 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter18;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter2 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter1;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter20 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter19;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter21 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter20;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter22 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter21;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter3 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter2;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter4 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter3;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter5 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter4;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter6 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter5;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter7 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter6;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter8 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter7;
        ap_reg_ppstg_tmp_112_reg_800_pp0_iter9 <= ap_reg_ppstg_tmp_112_reg_800_pp0_iter8;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter10 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter9;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter11 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter10;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter12 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter11;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter13 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter12;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter14 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter13;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter15 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter14;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter16 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter15;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter17 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter16;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter18 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter17;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter19 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter18;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter2 <= tmp_140_reg_839;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter20 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter19;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter21 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter20;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter22 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter21;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter3 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter2;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter4 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter3;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter5 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter4;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter6 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter5;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter7 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter6;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter8 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter7;
        ap_reg_ppstg_tmp_140_reg_839_pp0_iter9 <= ap_reg_ppstg_tmp_140_reg_839_pp0_iter8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == tmp_112_fu_463_p2))) begin
        i_2_reg_819 <= i_2_fu_504_p3;
        jj_1_reg_826 <= jj_1_fu_512_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter21) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)))) begin
        input_addr_read_reg_870 <= m_axi_input_r_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter13))) begin
        input_addr_reg_864 <= sum_cast_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == tmp_112_reg_800))) begin
        j_2_reg_834 <= j_2_fu_524_p3;
        tmp_140_reg_839 <= tmp_140_fu_607_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        n_cols_2_reg_774 <= n_cols_2_fu_438_p3;
        tmp1_reg_780 <= grp_fu_377_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        n_cols_reg_753 <= n_cols_fu_402_p3;
        tmp5_reg_759 <= tmp5_fu_410_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        n_depth_1_reg_738 <= n_depth_1_fu_357_p3;
        n_rows_2_reg_732 <= n_rows_2_fu_334_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        n_rows_reg_700 <= n_rows_fu_274_p3;
        tmp_101_reg_711 <= tmp_101_fu_294_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        sext_cast_reg_795[29 : 0] <= sext_cast_fu_455_p1[29 : 0];
        tmp_111_reg_790 <= grp_fu_451_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter6))) begin
        tmp16_reg_854 <= tmp16_fu_623_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == tmp_112_fu_463_p2))) begin
        tmp_113_reg_809 <= tmp_113_fu_474_p2;
        tmp_114_reg_814 <= tmp_114_fu_493_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter5))) begin
        tmp_115_reg_849 <= grp_fu_532_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter12))) begin
        tmp_116_reg_859 <= tmp_116_fu_636_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st19_fsm_18)) begin
        tmp_88_reg_785 <= grp_fu_416_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        tmp_89_reg_676 <= grp_fu_253_p2;
        tmp_92_reg_681 <= grp_fu_247_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        tmp_95_reg_743 <= grp_fu_381_p2;
        tmp_98_reg_748 <= grp_fu_288_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | (1'b1 == ap_sig_cseq_ST_st45_fsm_21))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st45_fsm_21)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_301) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_20 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_20 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_569) begin
        ap_sig_cseq_ST_st10_fsm_9 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_245) begin
        ap_sig_cseq_ST_st12_fsm_11 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_256) begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_267) begin
        ap_sig_cseq_ST_st14_fsm_13 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_608) begin
        ap_sig_cseq_ST_st15_fsm_14 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_14 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_282) begin
        ap_sig_cseq_ST_st19_fsm_18 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_18 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_39) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_291) begin
        ap_sig_cseq_ST_st20_fsm_19 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_19 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_822) begin
        ap_sig_cseq_ST_st45_fsm_21 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st45_fsm_21 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_500) begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_200) begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_211) begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_228) begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_560) begin
        ap_sig_cseq_ST_st9_fsm_8 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_m_axi_input_r_ARREADY)) begin
        ap_sig_ioackin_m_axi_input_r_ARREADY = m_axi_input_r_ARREADY;
    end else begin
        ap_sig_ioackin_m_axi_input_r_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)))) begin
        grp_fu_532_ce = 1'b1;
    end else begin
        grp_fu_532_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)))) begin
        grp_fu_628_ce = 1'b1;
    end else begin
        grp_fu_628_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(1'b0 == tmp_112_reg_800))) begin
        i_phi_fu_211_p4 = i_2_reg_819;
    end else begin
        i_phi_fu_211_p4 = i_reg_207;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14))) begin
        input_r_blk_n_AR = m_axi_input_r_ARREADY;
    end else begin
        input_r_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it22) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter21))) begin
        input_r_blk_n_R = m_axi_input_r_RVALID;
    end else begin
        input_r_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it23) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)))) begin
        inputfm_ce0 = 1'b1;
    end else begin
        inputfm_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it23) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter22))) begin
        inputfm_we0 = 1'b1;
    end else begin
        inputfm_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(1'b0 == tmp_112_reg_800))) begin
        j_phi_fu_222_p4 = j_4_fu_613_p2;
    end else begin
        j_phi_fu_222_p4 = j_reg_218;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_20) & ~(1'b0 == tmp_112_reg_800))) begin
        jj_phi_fu_234_p4 = jj_1_reg_826;
    end else begin
        jj_phi_fu_234_p4 = jj_reg_230;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & ~((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309) & (1'b0 == ap_reg_ioackin_m_axi_input_r_ARREADY))) begin
        m_axi_input_r_ARVALID = 1'b1;
    end else begin
        m_axi_input_r_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it22) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter21) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)))) begin
        m_axi_input_r_RREADY = 1'b1;
    end else begin
        m_axi_input_r_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : begin
            ap_NS_fsm = ap_ST_st15_fsm_14;
        end
        ap_ST_st15_fsm_14 : begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : begin
            ap_NS_fsm = ap_ST_st17_fsm_16;
        end
        ap_ST_st17_fsm_16 : begin
            ap_NS_fsm = ap_ST_st18_fsm_17;
        end
        ap_ST_st18_fsm_17 : begin
            ap_NS_fsm = ap_ST_st19_fsm_18;
        end
        ap_ST_st19_fsm_18 : begin
            ap_NS_fsm = ap_ST_st20_fsm_19;
        end
        ap_ST_st20_fsm_19 : begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_20;
        end
        ap_ST_pp0_stg0_fsm_20 : begin
            if ((~((1'b1 == ap_reg_ppiten_pp0_it23) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b1 == ap_reg_ppiten_pp0_it22)) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & (1'b0 == tmp_112_fu_463_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_20;
            end else if ((((1'b1 == ap_reg_ppiten_pp0_it23) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & ~(1'b1 == ap_reg_ppiten_pp0_it22)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14) & (1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) | ((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309)) & (1'b0 == tmp_112_fu_463_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st45_fsm_21;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_20;
            end
        end
        ap_ST_st45_fsm_21 : begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_173 = ((1'b1 == ap_reg_ppiten_pp0_it15) & ~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter14));
end

always @ (*) begin
    ap_sig_200 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_211 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_228 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_245 = (1'b1 == ap_CS_fsm[ap_const_lv32_B]);
end

always @ (*) begin
    ap_sig_256 = (1'b1 == ap_CS_fsm[ap_const_lv32_C]);
end

always @ (*) begin
    ap_sig_267 = (1'b1 == ap_CS_fsm[ap_const_lv32_D]);
end

always @ (*) begin
    ap_sig_282 = (1'b1 == ap_CS_fsm[ap_const_lv32_12]);
end

always @ (*) begin
    ap_sig_291 = (1'b1 == ap_CS_fsm[ap_const_lv32_13]);
end

always @ (*) begin
    ap_sig_301 = (1'b1 == ap_CS_fsm[ap_const_lv32_14]);
end

always @ (*) begin
    ap_sig_309 = (~(1'b0 == ap_reg_ppstg_tmp_112_reg_800_pp0_iter21) & (m_axi_input_r_RVALID == 1'b0));
end

always @ (*) begin
    ap_sig_39 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_500 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_560 = (1'b1 == ap_CS_fsm[ap_const_lv32_8]);
end

always @ (*) begin
    ap_sig_569 = (1'b1 == ap_CS_fsm[ap_const_lv32_9]);
end

always @ (*) begin
    ap_sig_608 = (1'b1 == ap_CS_fsm[ap_const_lv32_E]);
end

always @ (*) begin
    ap_sig_822 = (1'b1 == ap_CS_fsm[ap_const_lv32_15]);
end

always @ (*) begin
    ap_sig_874 = ((1'b1 == m_axi_input_r_ARREADY) & ~((1'b1 == ap_reg_ppiten_pp0_it22) & ap_sig_309));
end

assign grp_fu_247_p1 = ($signed(curr_layer_out_h) + $signed(ap_const_lv32_FFFFFFFF));

assign grp_fu_253_p1 = ap_const_lv32_19;

assign grp_fu_288_p1 = ($signed(curr_layer_out_w) + $signed(ap_const_lv32_FFFFFFFF));

assign grp_fu_381_p1 = ap_const_lv32_19;

assign i_2_fu_504_p3 = ((tmp_114_fu_493_p2[0:0] === 1'b1) ? ap_const_lv32_0 : p_i_fu_485_p3);

assign i_4_fu_479_p2 = (ap_const_lv32_1 + i_phi_fu_211_p4);

assign inputfm_address0 = tmp_141_cast_fu_660_p1;

assign inputfm_d0 = input_addr_read_reg_870;

assign itr_2_fu_468_p2 = (itr_reg_196 + ap_const_lv31_1);

assign itr_cast_fu_459_p1 = itr_reg_196;

assign j_2_fu_524_p3 = ((tmp_74_fu_520_p2[0:0] === 1'b1) ? ap_const_lv32_0 : j_reg_218);

assign j_4_fu_613_p2 = (ap_const_lv32_1 + j_2_fu_524_p3);

assign jj_1_fu_512_p3 = ((tmp_114_fu_493_p2[0:0] === 1'b1) ? jj_2_fu_498_p2 : jj_phi_fu_234_p4);

assign jj_2_fu_498_p2 = (ap_const_lv32_1 + jj_phi_fu_234_p4);

assign m_axi_input_r_ARADDR = input_addr_reg_864;

assign m_axi_input_r_ARBURST = ap_const_lv2_0;

assign m_axi_input_r_ARCACHE = ap_const_lv4_0;

assign m_axi_input_r_ARID = 1'b0;

assign m_axi_input_r_ARLEN = ap_const_lv32_1;

assign m_axi_input_r_ARLOCK = ap_const_lv2_0;

assign m_axi_input_r_ARPROT = ap_const_lv3_0;

assign m_axi_input_r_ARQOS = ap_const_lv4_0;

assign m_axi_input_r_ARREGION = ap_const_lv4_0;

assign m_axi_input_r_ARSIZE = ap_const_lv3_0;

assign m_axi_input_r_ARUSER = 1'b0;

assign m_axi_input_r_AWADDR = ap_const_lv32_0;

assign m_axi_input_r_AWBURST = ap_const_lv2_0;

assign m_axi_input_r_AWCACHE = ap_const_lv4_0;

assign m_axi_input_r_AWID = 1'b0;

assign m_axi_input_r_AWLEN = ap_const_lv32_0;

assign m_axi_input_r_AWLOCK = ap_const_lv2_0;

assign m_axi_input_r_AWPROT = ap_const_lv3_0;

assign m_axi_input_r_AWQOS = ap_const_lv4_0;

assign m_axi_input_r_AWREGION = ap_const_lv4_0;

assign m_axi_input_r_AWSIZE = ap_const_lv3_0;

assign m_axi_input_r_AWUSER = 1'b0;

assign m_axi_input_r_AWVALID = 1'b0;

assign m_axi_input_r_BREADY = 1'b0;

assign m_axi_input_r_WDATA = ap_const_lv32_0;

assign m_axi_input_r_WID = 1'b0;

assign m_axi_input_r_WLAST = 1'b0;

assign m_axi_input_r_WSTRB = ap_const_lv4_0;

assign m_axi_input_r_WUSER = 1'b0;

assign m_axi_input_r_WVALID = 1'b0;

assign n_cols_2_fu_438_p3 = ((tmp_106_fu_426_p2[0:0] === 1'b1) ? tmp_107_fu_432_p2 : n_cols_reg_753);

assign n_cols_fu_402_p3 = ((tmp_100_fu_396_p2[0:0] === 1'b1) ? tmp_96_fu_386_p2 : tmp_99_fu_391_p2);

assign n_depth_1_fu_357_p3 = ((tmp_109_fu_347_p2[0:0] === 1'b1) ? tmp_110_fu_352_p2 : n_depth_fu_311_p3);

assign n_depth_fu_311_p3 = ((tmp_101_reg_711[0:0] === 1'b1) ? ap_const_lv32_A : curr_layer_in_ch);

assign n_rows_2_fu_334_p3 = ((tmp_103_fu_322_p2[0:0] === 1'b1) ? tmp_104_fu_328_p2 : n_rows_reg_700);

assign n_rows_fu_274_p3 = ((tmp_94_fu_268_p2[0:0] === 1'b1) ? tmp_90_fu_258_p2 : tmp_93_fu_263_p2);

assign p_i_fu_485_p3 = ((tmp_113_fu_474_p2[0:0] === 1'b1) ? i_4_fu_479_p2 : i_phi_fu_211_p4);

assign p_shl2_cast_fu_593_p3 = {{tmp_138_fu_589_p1}, {ap_const_lv4_0}};

assign p_shl3_cast_fu_550_p1 = $signed(tmp_133_fu_543_p3);

assign p_shl4_cast_fu_561_p1 = $signed(tmp_134_fu_554_p3);

assign p_shl_cast_fu_581_p3 = {{tmp_137_fu_577_p1}, {ap_const_lv6_0}};

assign sext_cast_fu_455_p1 = image1;

assign sum_cast_fu_650_p1 = $signed(sum_fu_645_p2);

assign sum_fu_645_p2 = ($signed(tmp_117_cast_fu_642_p1) + $signed(sext_cast_reg_795));

assign tmp16_fu_623_p2 = (tmp_fu_619_p2 + tmp5_reg_759);

assign tmp2_fu_632_p2 = (tmp_88_reg_785 + ap_reg_ppstg_j_2_reg_834_pp0_iter12);

assign tmp5_fu_410_p2 = (grp_fu_300_p2 + grp_fu_306_p2);

assign tmp_100_fu_396_p2 = (($signed(tmp_96_fu_386_p2) < $signed(tmp_99_fu_391_p2)) ? 1'b1 : 1'b0);

assign tmp_101_fu_294_p2 = (($signed(curr_layer_in_ch) > $signed(32'b1010)) ? 1'b1 : 1'b0);

assign tmp_102_fu_317_p0 = row;

assign tmp_102_fu_317_p2 = ($signed(tmp_102_fu_317_p0) + $signed(n_rows_reg_700));

assign tmp_103_fu_322_p1 = curr_layer_in_h;

assign tmp_103_fu_322_p2 = (($signed(tmp_102_fu_317_p2) > $signed(tmp_103_fu_322_p1)) ? 1'b1 : 1'b0);

assign tmp_104_fu_328_p0 = curr_layer_in_h;

assign tmp_104_fu_328_p1 = row;

assign tmp_104_fu_328_p2 = ($signed(tmp_104_fu_328_p0) - $signed(tmp_104_fu_328_p1));

assign tmp_105_fu_421_p0 = col;

assign tmp_105_fu_421_p2 = ($signed(tmp_105_fu_421_p0) + $signed(n_cols_reg_753));

assign tmp_106_fu_426_p1 = curr_layer_in_w;

assign tmp_106_fu_426_p2 = (($signed(tmp_105_fu_421_p2) > $signed(tmp_106_fu_426_p1)) ? 1'b1 : 1'b0);

assign tmp_107_fu_432_p0 = curr_layer_in_w;

assign tmp_107_fu_432_p1 = col;

assign tmp_107_fu_432_p2 = ($signed(tmp_107_fu_432_p0) - $signed(tmp_107_fu_432_p1));

assign tmp_108_fu_341_p0 = ti;

assign tmp_108_fu_341_p2 = ($signed(tmp_108_fu_341_p0) + $signed(n_depth_fu_311_p3));

assign tmp_109_fu_347_p2 = (($signed(tmp_108_fu_341_p2) > $signed(curr_layer_in_ch)) ? 1'b1 : 1'b0);

assign tmp_110_fu_352_p1 = ti;

assign tmp_110_fu_352_p2 = ($signed(curr_layer_in_ch) - $signed(tmp_110_fu_352_p1));

assign tmp_112_fu_463_p2 = (($signed(itr_cast_fu_459_p1) < $signed(tmp_111_reg_790)) ? 1'b1 : 1'b0);

assign tmp_113_fu_474_p2 = ((j_phi_fu_222_p4 == n_cols_2_reg_774) ? 1'b1 : 1'b0);

assign tmp_114_fu_493_p2 = ((p_i_fu_485_p3 == n_rows_2_reg_732) ? 1'b1 : 1'b0);

assign tmp_116_fu_636_p2 = (grp_fu_628_p2 + tmp2_fu_632_p2);

assign tmp_117_cast_fu_642_p1 = $signed(tmp_116_reg_859);

assign tmp_119_cast_fu_540_p1 = $signed(i_2_reg_819);

assign tmp_132_fu_536_p1 = j_2_fu_524_p3[16:0];

assign tmp_133_fu_543_p3 = {{jj_1_reg_826}, {ap_const_lv6_0}};

assign tmp_134_fu_554_p3 = {{jj_1_reg_826}, {ap_const_lv4_0}};

assign tmp_135_fu_565_p2 = ($signed(p_shl3_cast_fu_550_p1) + $signed(p_shl4_cast_fu_561_p1));

assign tmp_136_fu_571_p2 = ($signed(tmp_119_cast_fu_540_p1) + $signed(tmp_135_fu_565_p2));

assign tmp_137_fu_577_p1 = tmp_136_fu_571_p2[10:0];

assign tmp_138_fu_589_p1 = tmp_136_fu_571_p2[12:0];

assign tmp_139_fu_601_p2 = (p_shl_cast_fu_581_p3 + p_shl2_cast_fu_593_p3);

assign tmp_140_fu_607_p2 = (tmp_132_fu_536_p1 + tmp_139_fu_601_p2);

assign tmp_141_cast_fu_660_p1 = ap_reg_ppstg_tmp_140_reg_839_pp0_iter22;

assign tmp_74_fu_520_p2 = (tmp_114_reg_814 | tmp_113_reg_809);

assign tmp_90_fu_258_p2 = (curr_layer_ker_h + tmp_89_reg_676);

assign tmp_93_fu_263_p2 = (curr_layer_ker_h + tmp_92_reg_681);

assign tmp_94_fu_268_p2 = (($signed(tmp_90_fu_258_p2) < $signed(tmp_93_fu_263_p2)) ? 1'b1 : 1'b0);

assign tmp_96_fu_386_p2 = (curr_layer_ker_w + tmp_95_reg_743);

assign tmp_99_fu_391_p2 = (curr_layer_ker_w + tmp_98_reg_748);

assign tmp_fu_619_p2 = (ap_reg_ppstg_i_2_reg_819_pp0_iter6 + tmp_115_reg_849);

always @ (posedge ap_clk) begin
    sext_cast_reg_795[32:30] <= 3'b000;
end

endmodule //zhang_cnn_read_input
