// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_zhang_cnn (
unsigned char* image,
unsigned char* weights,
volatile unsigned char* out,
layer_config curr_layer_in,
int input_offset,
int weights_offset,
int output_offset,
int quantized_multiplier,
int right_shift);
